name: Robot Framework - Python
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
permissions:
  contents: read
 
jobs:
  test:
    runs-on: ubuntu-latest
     
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.1
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
   
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Downgrade Chrome browser to v114
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 1134343 # Last commit number for Chrome v114
        id: setup-chrome
      - run: sudo ln -fs ${{ steps.setup-chrome.outputs.chrome-path }} /usr/bin/google-chrome
      - name: Downgrade Chrome driver to v114
        run: php artisan dusk:chrome-driver `/usr/bin/google-chrome --version | cut -d " " -f3 | cut -d "." -f1`
      - name: Test with RobotFramework
        run: robot -d ./results tests
         
      - name: Test Report Generation
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Report                # Name of the folder
          path: results           # Path to test results



