name: robot-expandtesting_UI_and_API
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
permissions:
  contents: read
 
jobs:
  tests:
    runs-on: ubuntu-latest
    name: E2E Tests 

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies 
        run: pip install -r requirements.txt

      - name: Run tests 
        run: robot -d ./results tests

      - name: Publish Robot Reports 
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Robot-Reports
          path: reports
          retention-days: 90
          if-no-files-found: warn


